apiVersion: v1
kind: Pod
metadata:
  name: pod-env
  labels:
    name: pod-env
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: GREETING
      value: "Welcome to"
    - name: COMPANY
      value: "DevOps"
    - name: GROUP
      value: "Industries"
    command: ["echo"]
    args: ["$(GREETING) $(COMPANY) $(GROUP)"]
    
    