apiVersion: v1
kind: Pod
metadata:
  name: pot-init
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
  initContainers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "300"
