apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: storage
          mountPath: "/var/www/html"
  volumes:
    - name: storage
      persistentVolumeClaim: 
        claimName: claim-log-1