apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev_deploy
  labels:
    app: dev_deploy
  Namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev_deploy
  containers:
  - name: app
    image: redis
    resources:
      requests:
        memory: "1G"
        cpu: ".5 vcpu"
      limits:
        memory: "2G"
        cpu: "1 vcpu"
  