apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
      - name: deployment-1
        image: nginx
        command:
        -  sleep
        -  "3000"
        