apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
  namespace: dev
  labels:
    app: dev-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-deploy
  template:
    metadata:
      labels:
        app: dev-deploy
    spec:
      containers:
      - name: app
        image: redis
        resources:
          requests:
            memory: "1G"
            cpu: ".500m"
          limits:
            memory: "2G"
            cpu: "1000m"
  